### ISSUE TITLE
Not possible to browse pictures in gallery

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#408] opened 2015-10-06 10:33 UTC
Gallery: It is not possible to browse pictures in lightbox.
Reference: http://swiss.github.io/styleguide/content_modules_-_multimedia.html#a-photo-gallery-overview 

![komponente 20bildergalerie 20galerie 20lightbox 20keine 20arro 20icons](https://cloud.githubusercontent.com/assets/9591815/10306318/6724d566-6c26-11e5-96ae-b322c9d4b609.png)

**Comment by tonifisler** [comment] 2015-10-27 17:47
Duplicate of #402

**Closed by tonifisler** 2015-10-27 17:47 UTC
Labels: enhancement
