### ISSUE TITLE
Homepage without global navigation: Focus problem on Site Map in Internet Explorer

### ISSUE THREAD

**Issue by ccweb** [swiss/styleguide#504] opened 2017-01-24 15:52 UTC
On a Homepage without global navigation i click on a link in the Site Map. Then i hit the back button in the browser. Now the link below the previously clicked link receives the keyboard focus (thik black border)
e. g. http://www.esbk.admin.ch/esbk/en/home.html. Click  on «The Commission of the Federal Gaming Board (FGB)» first and then hit the back button in the browser. Now the Link below receives the keyboard focus.
![fgb](https://cloud.githubusercontent.com/assets/7446943/22254464/f076dd00-e254-11e6-8060-61d765a23a58.png)
Can't be tested within the webguidelines, because there aren't any subpages.

**Comment by mbruellmann** [comment] 2017-09-27 07:29
We cannot reproduce this issue. Is it still a problem? Please advice.

**Comment by ccweb** [comment] 2017-09-27 09:39
Yes, the problem persists. In addition to the page mentioned above it can be reproduced on the following pages https://www.nkvf.admin.ch/nkvf/en/home.html or https://www.eschk.admin.ch/eschk/de/home.html
None of the other federal departments uses the [Homepage without global navigation](https://swiss.github.io/styleguide/en/pages/02.home-without-nav.html) template.
This is why the problem only exists on pages published by the Federal Department of Justice and Police (FDJP).

**Comment by gillerr** [comment] 2019-12-09 10:04
test again, is this still an issue?

**Comment by gillerr** [comment] 2019-12-09 10:07
Won't fix

**Closed by gillerr** 2019-12-09 10:07 UTC
