### ISSUE TITLE
News don't have the right display for tablet portrait - should be only one column

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#362] opened 2015-03-17 13:20 UTC
News are always display one under the other, but not for the tablet portrait format where they suddenly are displayed 3 next to each other, which is not correct. The styling of the column control should be adapted so that each new is dislayed on the full width, and so that the next new is displayed under the first one. 

![medienmitteilungen 20hochformat 20tablet](https://cloud.githubusercontent.com/assets/7644740/6688041/a30e340c-ccb0-11e4-99c2-f8035d3d8a63.png)

**Comment by tonifisler** [comment] 2015-03-17 18:59
Does this happen in the styleguide too? This looks like a faulty implementation of the bootstrap columns from the developer.

**Comment by desobryc** [comment] 2015-03-18 12:10
I don't know as I cannot find an example I could test in the styleguide. It has to be a news feed which is displayed on a normal content page with a left handside navigation. Can you help me?

**Comment by tonifisler** [comment] 2015-03-19 17:20
This is indeed happening because of the integration developer. Faulty code:

```css
@media (max-width: 991px) and (min-width: 768px) {
  .mod-nsbnewslist .news-feed .list-group-item {
    width: 33%;
  }
}
```

I'm closing this issue because it is not an issue caused by the styleguide.

**Closed by tonifisler** 2015-03-19 17:20 UTC
Labels: bug

**Comment by desobryc** [comment] 2015-03-19 19:50
Thanks for your help!
