### ISSUE TITLE
not only already clicked links are shown violet

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#352] opened 2015-01-23 15:01 UTC
Browser affected: Chrome, Firefox
If I clic on one of links of the example pages, than all links become violet at the same time: 
![image](https://cloud.githubusercontent.com/assets/7644740/5876603/cd4c2b50-a318-11e4-96df-c311b53e0724.png)

**Comment by tonifisler** [comment] 2015-01-23 15:05
This was already reported several times and we must insist that it is completely normal. Those links are fake and point to `href="#"`... Duplicate of #336 and #269

**Closed by tonifisler** 2015-01-23 15:05 UTC
