### ISSUE TITLE
Space in footer appearing without any content. 

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#293] opened 2014-11-27 13:35 UTC
Description: Space for social-links appears without any content. White divide appears always too. 

Browser: all 

For further information or if you have any questions please do not hesitate to contact me. lukas.jaborsky@namics.com

Screenshot: 
![divide](https://cloud.githubusercontent.com/assets/3909997/5217587/a3057d90-7642-11e4-9fd4-743cdca8b780.png)

**Comment by tonifisler** [comment] 2015-01-19 16:44
Hey @LukasJaborsky, coming back to you with this issue. I think there's an error with your markup, given the added white margin at the left of the block. I can't reproduce it, even by copy-pasting the code you provided.

Are you still experiencing this issue? Thanks.

**Comment by tonifisler** [comment] 2015-01-19 16:45
![screen shot 2015-01-19 at 17 44 57](https://cloud.githubusercontent.com/assets/1708450/5804026/ebaf24bc-a002-11e4-8be7-c8b2779a9141.png)

**Comment by LukasJaborsky** [comment] 2015-01-21 08:49
Hi @tonifisler, i cant reproduce it too. Mabye ist was fixed with the latest release.

**Comment by tonifisler** [comment] 2015-01-21 08:53
Great! I'll close this issue then. Next release coming in a few days. :trophy:

**Closed by tonifisler** 2015-01-21 08:53 UTC
Labels: cms.nextgen, enhancement, waiting for answer
